[workspace]
members = [
    "contracts/factory",
    "contracts/pair",
    "contracts/lp_token",
    "contracts/router",
    "contracts/flash_receiver_interface",
    "contracts/mock_flash_receiver",
    "tests/fuzz"
]
resolver = "2"

[workspace.dependencies]
soroban-sdk = "27.0.2"
soroban-token-sdk = "27.0.2"
soroban-env-common = "27.0.2"
soroban-env-host = "27.0.2"
soroban-env-guest = "27.0.2"
ethnum = "1.5.3"

[profile.release]
overflow-checks = true
opt-level = "z"
debug = false